# Generated by Django 4.0.3 on 2022-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_qrcode_code_attendancestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, default='c65dd3467b9f35f523a4a4504cfeb657', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AttendanceStatus',
        ),
    ]
