# Generated by Django 4.0.3 on 2022-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_qrcode_code_delete_attendancestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, default='debad05a466ed326185f97997a361fbb', max_length=100, null=True),
        ),
    ]
